#cloud-config
users: # Collection von Benutzern
  - name: ubuntu # Der Benutzername des Benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für Benutzer
    groups: users, admin # Die zugewiesenen Gruppen des Benutzers
    home: /home/ubuntu # Heimverzeichniss des Benutzers
    shell: /bin/bash # Standard Shell des Benutzers
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfji6iNpeDP98/frSmYEPEN2JQP+nVGIKp5yq5QLWhO8Yjy/+aI05ArvqNTiuAn2ojsSnGp/0MW96tMzp7P/tKwEOipqZ/5bTFx4wHCFiNeSJbayjXu9QU8wJg8FEc6G8cabpo+yieCYNM5/NaKvnNwmmB4Qp5AoBGD8510vZbWQdE9GBaDkaj9FeFFTGVxs8hyrr4oCWrKc4iSwg+qzEyyatwUYccMotOX3+bHLnUmGewUs48nzxALL5xOm1JSc/UMjk+0Lr83rk1LVtPTcj6SPdiTRFDNL+DWeeDLXkER4iXhaf7Rp1uUjZihHsdrm+4jrx5fR883uCFSqlO7Vux aws-key

ssh_pwauth: false # Beim versuch einer SSH Verbindung nach Passwort Authentifizierung fragen
disable_root: false # Root login de/aktivieren
packages: # Welche packages sollten vorinstalliert werden
  - mariadb-server

runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY'password' WITH GRANT OPTION;"
  - sudo sed -i's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb
