#cloud-config
users: # Collection von Benutzern
  - name: ubuntu # Der Benutzername des Benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für Benutzer
    groups: users, admin # Die zugewiesenen Gruppen des Benutzers
    home: /home/ubuntu # Heimverzeichniss des Benutzers
    shell: /bin/bash # Standard Shell des Benutzers
    lock_passwd: false # Kann der Benutzers sein Passwort ändern
    plain_text_passwd: 'password' # Das Passwort des Benutzers      
ssh_pwauth: true # Beim versuch einer SSH Verbindung nach Passwort Authentifizierung fragen
disable_root: false # Root login de/aktivieren
packages: # Welche packages sollten vorinstalliert werden
  - mariadb-server

runcmd:
  - "chown ubuntu:ubuntu /var/www/html/db.php"
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'ubuntu'@'%' IDENTIFIED BY'password' WITH GRANT OPTION;"