#cloud-config
users: # Collection von Benutzern
  - name: ubuntu # Der Benutzername des Benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für Benutzer
    groups: users, admin # Die zugewiesenen Gruppen des Benutzers
    home: /home/ubuntu # Heimverzeichniss des Benutzers
    shell: /bin/bash # Standard Shell des Benutzers
    lock_passwd: false # Kann der Benutzers sein Passwort ändern
    plain_text_passwd: 'password' # Das Passwort des Benutzers      
ssh_pwauth: true # Beim versuch einer SSH Verbindung nach Passwort Authentifizierung fragen
disable_root: false # Root login de/aktivieren
packages: # Welche packages sollten vorinstalliert werden
  - apache2 
  - curl 
  - wget 
  - php 
  - libapache2-mod-php 
  - php-mysqli
  - adminer

package-update: true
package_upgrade: true

write_files:

- content: |
    <?php
        //database
        $servername = "127.0.0.1";
        $username = "admin";
        $password = "password";
        $dbname = "mysql";

        // Create connection
        $conn = new mysqli($servername, $username, $password, $dbname);
        // Check connection
        if ($conn->connect_error) {
                die("Connection failed: " . $conn->connect_error);
        }

        $sql = "select Host, User from mysql.user;";
        $result = $conn->query($sql);
        while($row = $result->fetch_assoc()){
                echo($row["Host"] . " / " . $row["User"] . "<br />");
        }
        //var_dump($result);
    ?>

  path: /var/www/html/db.php
  permissions: "0644"

  runcmd:
  - "chown ubuntu:ubuntu /var/www/html/db.php"